//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CommonModels.Models.EntityFramework;

namespace CommonModels.Models.EntityFramework
{
	public partial class Author
    {
        public Author()
        {
            this.ProductGroups = new HashSet<ProductGroup>();
        }
    
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string DisplayName { get; set; }
        public string FriendlyUrl { get; set; }
        public string About { get; set; }
        public bool IsCheckedByAdmin { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<ProductGroup> ProductGroups { get; set; }
    }
}
