//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonModels.Models.EntityFramework
{
    using System;

	public partial class Feedback
    {
        public int ID { get; set; }
        public int UserOrderID { get; set; }
        public int RateGiverUserID { get; set; }
        public int RatedUserID { get; set; }
        public bool IsCustomers { get; set; }
        public Nullable<bool> IsPositive { get; set; }
        public bool WasSuccessful { get; set; }
        public byte ProductsQuality { get; set; }
        public byte SellerContact { get; set; }
        public byte TransactionQuality { get; set; }
        public byte TransportAndBoxing { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
    
        public virtual UserOrder UserOrder { get; set; }
        public virtual UserProfile RateGiverUser { get; set; }
        public virtual UserProfile RatedUser { get; set; }
    }
}
