//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonModels.Models.EntityFramework
{
	using System.Collections.Generic;
    
    public partial class HighlightType
    {
        public HighlightType()
        {
            this.HighlightedProductsInType = new HashSet<HighlightedProduct>();
        }
    
        public int ID { get; set; }
        public int Price { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<HighlightedProduct> HighlightedProductsInType { get; set; }
    }
}
