//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonModels.Models.EntityFramework
{
	public partial class HighlightedProduct
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int HighlightTypeID { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
    
        public virtual HighlightType HighlightType { get; set; }
        public virtual Product Product { get; set; }
    }
}
