//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonModels.Models.EntityFramework
{
	public partial class ProductInOrder
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int UserOrderID { get; set; }
        public int HowMany { get; set; }
        public int UnitPrice { get; set; }
        public bool IsForExchange { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual UserOrder UserOrder { get; set; }
    }
}
