//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonModels.Models.EntityFramework
{
	public partial class Rating
    {
        public int ID { get; set; }
        public int ProductGroupID { get; set; }
        public int UserID { get; set; }
        public byte Value { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual ProductGroup ProductGroup { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
