//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonModels.Models.EntityFramework
{
	using System.Collections.Generic;
    
    public partial class UserGroup
    {
        public UserGroup()
        {
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int ID { get; set; }
        public int Price { get; set; }
        public byte BuyFeePercent { get; set; }
        public byte SellFeePercent { get; set; }
        public byte MonthsToKeepBooks { get; set; }
        public string GroupName { get; set; }
    
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
