//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonModels.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOrder
    {
        public UserOrder()
        {
            this.Feedbacks = new HashSet<Feedback>();
            this.ProductsInOrder = new HashSet<ProductInOrder>();
        }
    
        public int ID { get; set; }
        public int CustomerUserProfileID { get; set; }
        public Nullable<int> CustomerAddressID { get; set; }
        public int CustomersBuyFeePercent { get; set; }
        public int VendorUserProfileID { get; set; }
        public Nullable<int> VendorAddressID { get; set; }
        public int VendorsSellFeePercent { get; set; }
        public int SumBookPrice { get; set; }
        public string SumOtherPrices { get; set; }
        public byte Status { get; set; }
        public byte RatingState { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual ICollection<ProductInOrder> ProductsInOrder { get; set; }
        public virtual UserAddress CustomerAddress { get; set; }
        public virtual UserProfile CustomerUserProfile { get; set; }
        public virtual UserProfile VendorUserProfile { get; set; }
        public virtual UserAddress VendorAddress { get; set; }
    }
}
